Import('base_env', 'debug_env', 'release_env', 'build_info')
from SCons.Script import Dir, Return

platform = build_info['platform']
architecture = build_info['architecture']
compiler = build_info['compiler']
config = build_info['config']
config_name = config.capitalize()
vsproj = build_info['vsproj']

current_env = debug_env if config.lower() == 'debug' else release_env

theorem_src_dir = Dir('../../Theorem/Source')
theorem_sources = theorem_src_dir.glob('*.cpp')

current_env.Append(CPPPATH=[
    '../../Theorem/Source',
    '../../Axiom/Source',
    '../../Axiom/Source/Axiom',
])

current_env.Prepend(LIBS=['Axiom', 'ImGui'])

current_env['OBJPREFIX'] = f'../Bin-Int/{platform}-{architecture}/{config_name}/'

theorem_program = current_env.Program('Theorem', theorem_sources)

theorem_project = None
if vsproj:
    theorem_headers = theorem_src_dir.glob('*.h')

    current_env['CPPPATH'] = [Dir(path) for path in current_env['CPPPATH']]
    variant_key = f'{config_name}|x64'
    dbg = {'LocalDebuggerWorkingDirectory': r'$(ProjectDir)..\\Build\\Theorem'}

    theorem_project = current_env.MSVSProject(
        target='../../Theorem/Theorem' + current_env['MSVSPROJECTSUFFIX'],
        srcs=[str(f) for f in theorem_sources],
        incs=[str(f) for f in theorem_headers],
        buildtarget=theorem_program,
        variant=[variant_key],
        auto_build_solution=0,
        DebugSettings=dbg
    )

Return('theorem_program', 'theorem_project')