Import('baseEnv', 'debugEnv', 'releaseEnv', 'buildInfo', 'axiomLib')

from SCons.Script import Dir, Return

platform = buildInfo['platform']
architecture = buildInfo['architecture']
compiler = buildInfo['compiler']
config = buildInfo['config']
configName = config.capitalize()
vsproj = buildInfo['vsproj']

localEnv = (debugEnv if config.lower() == 'debug' else releaseEnv).Clone()

coreSources = Glob('Source/*.cpp')
coreSources += Glob('Source/*/*.cpp')

localEnv.Append(
    CPPPATH=[
        Dir('#/Theorem/Source'),
        Dir('#/Axiom/Source'),
    ],
    LIBPATH=[
        Dir(f'#/Bin/{configName}/Axiom')
    ]
)

localEnv.Prepend(LIBS=[axiomLib])

theoremApp = localEnv.Program(f'#Bin/{configName}/Theorem/Theorem', coreSources)

theoremProject = None
if vsproj:
    theoremSources = Glob('Source/*.cpp') + Glob('Source/*/*.cpp')
    theoremHeaders = Glob('Source/*.h') + Glob('Source/*/*.h')
    localEnv['CPPPATH'] = [Dir(path) for path in localEnv['CPPPATH']]

    debugSettings = {
        'WorkingDirectory': '$(TargetDir)',
    }

    theoremProject = localEnv.MSVSProject(
        target='#/Theorem/Theorem' + localEnv['MSVSPROJECTSUFFIX'],
        srcs=[str(f) for f in theoremSources],
        incs=[str(f) for f in theoremHeaders],
        buildtarget=theoremApp,
        variant=[f'{configName}|x64'],
        auto_build_solution=0,
        DebugSettings=debugSettings
    )

Return('theoremApp', 'theoremProject')