// This file is auto-generated by Reflection.py. Do not edit manually.

#include "ComponentReflection.h"
#include "CameraComponent.h"
#include "DirectionalLightComponent.h"
#include "MeshComponent.h"
#include "PhysicsComponent.h"
#include "Sprite2DComponent.h"
#include "TagComponent.h"
#include "TransformComponent.h"

namespace Axiom {
    std::unordered_map<std::type_index, ComponentInfo> ComponentReflection::componentRegistry;

    void ComponentReflection::init() {
        ComponentInfo info;
        // Registering MeshComponent from Source/Scene/Components/MeshComponent.h
        info.name = "MeshComponent";
        info.size = sizeof(MeshComponent);
        info.fields = {
            {"meshId", FieldType::AssetHandle, offsetof(MeshComponent, meshId)},
        };
        componentRegistry[std::type_index(typeid(MeshComponent))] = info;

        // Registering CameraComponent from Source/Scene/Components/CameraComponent.h
        info.name = "CameraComponent";
        info.size = sizeof(CameraComponent);
        info.fields = {
            {"isMainCamera", FieldType::Bool, offsetof(CameraComponent, isMainCamera)},
            {"isFixedAspectRatio", FieldType::Bool, offsetof(CameraComponent, isFixedAspectRatio)},
        };
        componentRegistry[std::type_index(typeid(CameraComponent))] = info;

        // Registering TagComponent from Source/Scene/Components/TagComponent.h
        info.name = "TagComponent";
        info.size = sizeof(TagComponent);
        info.fields = {
            {"tag", FieldType::String, offsetof(TagComponent, tag)},
        };
        componentRegistry[std::type_index(typeid(TagComponent))] = info;

        // Registering Sprite2DComponent from Source/Scene/Components/Sprite2DComponent.h
        info.name = "Sprite2DComponent";
        info.size = sizeof(Sprite2DComponent);
        info.fields = {
            {"textureId", FieldType::AssetHandle, offsetof(Sprite2DComponent, textureId)},
            {"textureAddressMode", FieldType::Enum, offsetof(Sprite2DComponent, textureAddressMode)},
            {"textureFilterMode", FieldType::Enum, offsetof(Sprite2DComponent, textureFilterMode)},
            {"color", FieldType::Color, offsetof(Sprite2DComponent, color)},
        };
        componentRegistry[std::type_index(typeid(Sprite2DComponent))] = info;

        // Registering DirectionalLightComponent from Source/Scene/Components/DirectionalLightComponent.h
        info.name = "DirectionalLightComponent";
        info.size = sizeof(DirectionalLightComponent);
        info.fields = {
            {"color", FieldType::Color, offsetof(DirectionalLightComponent, color)},
            {"intensity", FieldType::Float, offsetof(DirectionalLightComponent, intensity)},
        };
        componentRegistry[std::type_index(typeid(DirectionalLightComponent))] = info;

        // Registering PhysicsComponent from Source/Scene/Components/PhysicsComponent.h
        info.name = "PhysicsComponent";
        info.size = sizeof(PhysicsComponent);
        info.fields = {
            {"velocity", FieldType::Vec3, offsetof(PhysicsComponent, velocity)},
            {"acceleration", FieldType::Vec3, offsetof(PhysicsComponent, acceleration)},
        };
        componentRegistry[std::type_index(typeid(PhysicsComponent))] = info;

        // Registering TransformComponent from Source/Scene/Components/TransformComponent.h
        info.name = "TransformComponent";
        info.size = sizeof(TransformComponent);
        info.fields = {
            {"position", FieldType::Vec3, offsetof(TransformComponent, position)},
            {"rotation", FieldType::Vec3, offsetof(TransformComponent, rotation)},
            {"scale", FieldType::Vec3, offsetof(TransformComponent, scale)},
        };
        componentRegistry[std::type_index(typeid(TransformComponent))] = info;
    }

    void ComponentReflection::addComponent(Entity entity, const std::string& componentType, void* componentData) {
        if (componentType == "MeshComponent") {
            MeshComponent* comp = static_cast<MeshComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
        if (componentType == "CameraComponent") {
            CameraComponent* comp = static_cast<CameraComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
        if (componentType == "TagComponent") {
            TagComponent* comp = static_cast<TagComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
        if (componentType == "Sprite2DComponent") {
            Sprite2DComponent* comp = static_cast<Sprite2DComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
        if (componentType == "DirectionalLightComponent") {
            DirectionalLightComponent* comp = static_cast<DirectionalLightComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
        if (componentType == "PhysicsComponent") {
            PhysicsComponent* comp = static_cast<PhysicsComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
        if (componentType == "TransformComponent") {
            TransformComponent* comp = static_cast<TransformComponent*>(componentData);
            entity.addComponent(*comp);
            return;
        }
    }

} // namespace Axiom
