import os
import re

componentRegex = re.compile(r'AX_COMPONENT\s*(?:struct|class)\s+(\w+)\s*\{([^}]+)\}')
fieldRegex = re.compile(r'\s*(float|int|bool|std::string|Math::Vec2|Math::Vec3|Math::Vec4|Color|UUID)\s+(\w+)(?:\s*=[^;]+)?;')
fiedlMapping = {
    'float': 'FieldType::Float',
    'int': 'FieldType::Int',
    'bool': 'FieldType::Bool',
    'std::string': 'FieldType::String',
    'Math::Vec2': 'FieldType::Vec2',
    'Math::Vec3': 'FieldType::Vec3',
    'Math::Vec4': 'FieldType::Vec4',
    'Color': 'FieldType::Color',
    'UUID': 'FieldType::AssetHandle'
}

def getFieldType(fieldType):
    return fiedlMapping.get(fieldType, 'FieldType::None')

def generateReflection():
    components = []

    for root, dirs, files in os.walk('Source/Scene/Components'):
        for file in files:
            if file.endswith('.h'):
                filepath = os.path.join(root, file)
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                    matches = componentRegex.findall(content)
                    for compName, body in matches:
                        fields = fieldRegex.findall(body)
                        components.append((compName, filepath, fields))

    outFile = os.path.join('Source/Scene/Components', 'ComponentReflection.cpp')

    cppCode = "// This file is auto-generated by Reflection.py. Do not edit manually.\n\n"
    cppCode += "#include \"ComponentReflection.h\"\n"

    for compName, filepath, fields in components:
        cppCode += f"#include \"{compName}.h\"\n"

    cppCode += "\nnamespace Axiom {\n\n"
    cppCode += "std::unordered_map<std::type_index, ComponentInfo> ComponentReflection::componentRegistry;\n\n"

    cppCode += "void ComponentReflection::init() {\n"
    cppCode += "ComponentInfo info;\n"

    for compName, filepath, fields in components:
        cppCode += f"// Registering {compName} from {filepath}\n"
        cppCode += f"info.name = \"{compName}\";\n"
        cppCode += f"info.size = sizeof({compName});\n"
        cppCode += f"info.fields = {{\n"

        for fieldType, fieldName in fields:
            cppCode += f"{{\"{fieldName}\", {getFieldType(fieldType)}, offsetof({compName}, {fieldName})}},\n"

        cppCode += "};\n"
        cppCode += f"componentRegistry[std::type_index(typeid({compName}))] = info;\n\n"

    cppCode += "}\n\n"

    cppCode += "void ComponentReflection::addComponent(Entity entity, const std::string& componentType, void* componentData) {\n"

    for compName, _, fields in components:
        cppCode += f"if (componentType == \"{compName}\") {{\n"
        cppCode += f"{compName}* comp = static_cast<{compName}*>(componentData);\n"
        cppCode += "entity.addComponent(*comp);\n"
        cppCode += "return;\n"
        cppCode += "}\n"

    cppCode += "}\n\n"
    cppCode += "} // namespace Axiom\n"

    with open(outFile, 'w', encoding='utf-8') as f:
        f.write(cppCode)

if __name__ == "__main__":
    generateReflection()
